/**
 * What a build actually did, counted (spec 147).
 *
 * The brief asks for debug metrics, and is explicit about why: **the goal is not
 * to equalise DPS.** It is to compare problem-solving power and sustainability
 * across builds that solve problems differently. A table where six builds have
 * the same damage-per-second is not evidence of balance -- it is evidence that
 * five of them have been tuned into the sixth.
 *
 * So this counts the things the six *routes* are made of. Strength's row should
 * be high on staggers and executions and near zero on healing; Constitution's
 * should be high on damage taken and long on encounter length; Agility's should
 * show the smallest health expenditure per kill. A build whose row looks like
 * somebody else's row is the finding.
 *
 * A pure fold over {@link ServerSimEvent}. It reads no clock -- the tick is
 * handed to it -- keeps no reference to the world, and never influences it, so
 * a harness can collect it and the live server can ignore it at zero cost.
 */

import type { ServerSimEvent } from './types.js';

export interface BuildMetrics {
  /** Ticks the fight has been running, from the first event to the last. */
  readonly ticks: number;
  readonly damageDealt: number;
  readonly damageTaken: number;
  /** Absorbed by a shield rather than by health. Constitution's and Wisdom's. */
  readonly damageAbsorbed: number;
  readonly healingReceived: number;
  /** Blows landed, and how many of them found a weak point. */
  readonly hits: number;
  readonly weakPoints: number;
  readonly criticals: number;
  /** Guards this body broke, and had broken. */
  readonly staggersCaused: number;
  readonly staggersTaken: number;
  /** Ticks spent rooted by somebody else's blow -- time under crowd control. */
  readonly ticksStaggered: number;
  readonly resourceSpent: number;
  readonly resourceRestored: number;
  /** Casts committed to, and casts withdrawn from before the attack point. */
  readonly castsCommitted: number;
  readonly castsWithdrawn: number;
  /**
   * Ticks the body was committed to something and could not move.
   *
   * Sampled rather than derived from events, and the one number that makes
   * Agility legible: its whole product is a smaller fraction of each cycle spent
   * rooted, and no event reports "still rooted". Without this column a harness
   * measures Agility's *side effects* and reads it as a weak damage build.
   */
  readonly ticksRooted: number;
  /** Follow-throughs walked out of. Agility's whole loop, counted. */
  readonly backswingsCancelled: number;
  readonly kills: number;
  readonly deaths: number;
  /** Per-ability usage, so "what did this build actually press" is answerable. */
  readonly abilityUses: Readonly<Record<string, number>>;

  // --- the health economy (spec 156) --------------------------------------
  /** Restoration progress earned, and how much of it the elite guarantee was. */
  readonly restorationEarned: number;
  /** Motes generated by this body's kills, and how many were elite guarantees. */
  readonly motesGenerated: number;
  readonly motesGuaranteed: number;
  readonly motesCollected: number;
  /** Motes that faded untaken. The waste number that is not overheal. */
  readonly motesLost: number;
  /** What motes actually put back, and what would not fit. */
  readonly restorationCollected: number;
  readonly restorationWasted: number;
  /** Flask draughts this body committed to. */
  readonly fallbackUsed: number;
  /**
   * Progress by reason, summed.
   *
   * The column the brief actually asks for: *why* did this build get what it
   * got. A Perception row with no `weakPoint` line is a build whose route is
   * not working, and no aggregate number says that.
   */
  readonly restorationSources: Readonly<Record<string, number>>;
}

export const EMPTY_METRICS: BuildMetrics = {
  ticks: 0,
  damageDealt: 0,
  damageTaken: 0,
  damageAbsorbed: 0,
  healingReceived: 0,
  hits: 0,
  weakPoints: 0,
  criticals: 0,
  staggersCaused: 0,
  staggersTaken: 0,
  ticksStaggered: 0,
  resourceSpent: 0,
  resourceRestored: 0,
  castsCommitted: 0,
  castsWithdrawn: 0,
  ticksRooted: 0,
  backswingsCancelled: 0,
  kills: 0,
  deaths: 0,
  abilityUses: {},
  restorationEarned: 0,
  motesGenerated: 0,
  motesGuaranteed: 0,
  motesCollected: 0,
  motesLost: 0,
  restorationCollected: 0,
  restorationWasted: 0,
  fallbackUsed: 0,
  restorationSources: {},
};

/** Mutable while a fold is running. Frozen into a {@link BuildMetrics} at the end. */
type Working = {
  -readonly [K in keyof Omit<BuildMetrics, 'abilityUses' | 'restorationSources'>]: number;
} & {
  abilityUses: Record<string, number>;
  restorationSources: Record<string, number>;
};

function working(from: BuildMetrics): Working {
  return {
    ...from,
    abilityUses: { ...from.abilityUses },
    restorationSources: { ...from.restorationSources },
  };
}

/**
 * One tick of events, folded into one body's counters.
 *
 * `entityId` is whose row this is: the same event stream is folded once per
 * body being measured, and each fold picks out the half that concerns it. A
 * `hit` is damage dealt for the attacker and damage taken for the target, and
 * counting it once from each side is what makes the two rows comparable.
 *
 * Cast phases are read off `castStarted` (spec 144): a `Backswing` phase *is*
 * the attack point, so it is what "committed" counts. `castEnded` distinguishes
 * a withdrawal from a walked-out follow-through by its reason, which is exactly
 * the distinction Agility's loop turns on.
 */
export function foldMetrics(
  into: BuildMetrics,
  entityId: number,
  tick: number,
  events: readonly ServerSimEvent[],
  reasons: {
    readonly cancelled: number;
    readonly backswingCancelled: number;
    readonly backswingPhase: number;
  },
): BuildMetrics {
  const next = working(into);
  next.ticks = Math.max(next.ticks, tick);

  for (const event of events) {
    switch (event.kind) {
      case 'hit': {
        // A heal is reported as a hit against oneself with negative damage
        // (spec 062), so one code path covers both and the sign tells them apart.
        if (event.damage < 0) {
          if (event.targetId === entityId) next.healingReceived += -event.damage;
          break;
        }
        if (event.attackerId === entityId) {
          next.damageDealt += event.damage;
          next.hits += 1;
          if (event.weakPoint) next.weakPoints += 1;
          if (event.critical) next.criticals += 1;
          if (event.killed) next.kills += 1;
        }
        if (event.targetId === entityId) next.damageTaken += event.damage;
        break;
      }
      case 'poiseBroken':
        if (event.breakerId === entityId) next.staggersCaused += 1;
        if (event.entityId === entityId) {
          next.staggersTaken += 1;
          next.ticksStaggered += event.ticks;
        }
        break;
      case 'castStarted':
        if (event.entityId !== entityId) break;
        if (event.phase === reasons.backswingPhase) next.castsCommitted += 1;
        else next.abilityUses[event.abilityId] = (next.abilityUses[event.abilityId] ?? 0) + 1;
        break;
      case 'castEnded':
        if (event.entityId !== entityId) break;
        if (event.reason === reasons.cancelled) next.castsWithdrawn += 1;
        if (event.reason === reasons.backswingCancelled) next.backswingsCancelled += 1;
        break;
      case 'died':
        if (event.entityId === entityId) next.deaths += 1;
        break;
      case 'restoration': {
        if (event.entityId !== entityId) break;
        next.restorationEarned += event.progress;
        next.motesGenerated += event.motes;
        next.motesGuaranteed += event.guaranteed;
        // Summed by reason, which is what makes a route legible: a Perception
        // row with no `weakPoint` line is a build whose route is not working,
        // and no total says that. The *progress* each reason is worth, not the
        // bare fraction, so the lines add up to something comparable.
        for (const source of event.sources) {
          const share = event.progress * source.amount;
          next.restorationSources[source.reason] =
            (next.restorationSources[source.reason] ?? 0) + share;
        }
        break;
      }
      case 'mote':
        if (event.ownerId !== entityId) break;
        if (event.collected) {
          next.motesCollected += 1;
          next.restorationCollected += event.restored;
        } else {
          next.motesLost += 1;
        }
        next.restorationWasted += event.wasted;
        break;
      default:
        break;
    }
  }

  return { ...next, abilityUses: next.abilityUses, restorationSources: next.restorationSources };
}

/** One tick of posture: was this body rooted by its own commitment? */
export function foldPosture(into: BuildMetrics, rooted: boolean): BuildMetrics {
  return rooted ? { ...into, ticksRooted: into.ticksRooted + 1 } : into;
}

/**
 * Resource and shield movement, which no event reports.
 *
 * Sampled from the entity between ticks rather than derived from events,
 * because spending is not an event: `startCast` takes the cost silently and a
 * regen tick adds it back silently. The caller hands the before and after, and
 * this decides which direction it went -- so a build that spends and regains
 * the same pool twenty times reads as forty movements rather than as zero.
 */
export function foldResource(
  into: BuildMetrics,
  before: { readonly resource: number; readonly shield: number; readonly fallbackCharges?: number },
  after: { readonly resource: number; readonly shield: number; readonly fallbackCharges?: number },
): BuildMetrics {
  const delta = after.resource - before.resource;
  const absorbed = Math.max(0, before.shield - after.shield);
  // The flask, sampled the same way and for the same reason (spec 156): a
  // charge is spent silently at the commit. Counting only the *decrease* makes
  // the refund net itself out for free, so this is draughts actually drunk
  // rather than draughts started -- which is the number that says whether
  // insurance is being used as insurance.
  const charges = Math.max(0, (before.fallbackCharges ?? 0) - (after.fallbackCharges ?? 0));
  return {
    ...into,
    resourceSpent: into.resourceSpent + Math.max(0, -delta),
    resourceRestored: into.resourceRestored + Math.max(0, delta),
    damageAbsorbed: into.damageAbsorbed + absorbed,
    fallbackUsed: into.fallbackUsed + charges,
  };
}

/**
 * The comparisons the brief actually asks for.
 *
 * Every one is a *ratio*, because the raw totals are not comparable across
 * builds that fight for different lengths of time -- which is the whole point of
 * measuring an attrition build against a burst one.
 */
export interface BuildSummary {
  /** Damage per second of encounter. The number that is *not* the goal. */
  readonly dps: number;
  /** Health spent per kill. Agility's route should be lowest here. */
  readonly healthPerKill: number;
  /** How much of the incoming damage never reached health. */
  readonly absorbFraction: number;
  /** Weak points as a fraction of blows landed. Perception's row. */
  readonly weakPointRate: number;
  /** Guards broken per kill. Strength's row. */
  readonly staggersPerKill: number;
  /** Fraction of the fight spent rooted by somebody else. */
  readonly controlledFraction: number;
  /** Resource restored over resource spent. Above 1 is a build that never dries. */
  readonly resourceRatio: number;
  /** Follow-throughs walked out of, per attack committed. */
  readonly cancelRate: number;
  /** Fraction of the fight spent rooted by one's own commitment. Agility's row. */
  readonly rootedFraction: number;
  readonly kills: number;
  readonly deaths: number;

  // --- the health economy (spec 156) --------------------------------------
  /**
   * **The number the whole spec is tuned against.** Health restored minus health
   * lost, per kill.
   *
   * Negative is the ordinary case and is the design target: a competent player
   * is slightly health-negative over an ordinary encounter. Near zero is
   * excellent play. Positive over a long run means the economy pays for itself,
   * which is the failure the brief names -- nobody should return to full for
   * free.
   */
  readonly netHealthPerKill: number;
  /** Motes generated per kill. Below 1 by design; the meter is the throttle. */
  readonly motesPerKill: number;
  /** Of what motes carried, the fraction that actually landed. Wisdom's row. */
  readonly moteEfficiency: number;
  /** Draughts drunk per kill. A build leaning on insurance reads high here. */
  readonly fallbackPerKill: number;
}

export function summarise(metrics: BuildMetrics, tickRate: number): BuildSummary {
  const seconds = Math.max(1 / tickRate, metrics.ticks / tickRate);
  const kills = Math.max(1, metrics.kills);
  const incoming = metrics.damageTaken + metrics.damageAbsorbed;
  return {
    dps: metrics.damageDealt / seconds,
    healthPerKill: metrics.damageTaken / kills,
    absorbFraction: incoming > 0 ? metrics.damageAbsorbed / incoming : 0,
    weakPointRate: metrics.hits > 0 ? metrics.weakPoints / metrics.hits : 0,
    staggersPerKill: metrics.staggersCaused / kills,
    controlledFraction: metrics.ticks > 0 ? metrics.ticksStaggered / metrics.ticks : 0,
    resourceRatio: metrics.resourceSpent > 0 ? metrics.resourceRestored / metrics.resourceSpent : 0,
    cancelRate:
      metrics.castsCommitted > 0 ? metrics.backswingsCancelled / metrics.castsCommitted : 0,
    rootedFraction: metrics.ticks > 0 ? metrics.ticksRooted / metrics.ticks : 0,
    kills: metrics.kills,
    deaths: metrics.deaths,
    netHealthPerKill: (metrics.healingReceived - metrics.damageTaken) / kills,
    motesPerKill: metrics.motesGenerated / kills,
    moteEfficiency:
      metrics.restorationCollected + metrics.restorationWasted > 0
        ? metrics.restorationCollected /
          (metrics.restorationCollected + metrics.restorationWasted)
        : 0,
    fallbackPerKill: metrics.fallbackUsed / kills,
  };
}
