/**
 * Authoring pass for the arena map: the northern mountain, its serpentine road,
 * a spread-out encounter graph, and the Warden's arena on the eastern beach.
 *
 * Generated by Claude as a repeatable map-authoring script, and TypeScript like
 * the other 167 in this directory (spec 279's follow-up). It was written as
 * plain .mjs to stay out of `tsc --noEmit`, and that dodge does not survive
 * `eslint .`: the project service cannot resolve a file `tsconfig.json` does not
 * include, so the whole lint gate failed on it. Typed, it is checked by the same
 * three gates as everything else -- and the annotations are the only change,
 * so what it writes is what it wrote.
 *
 * Coordinate note, the one thing that will bite you here:
 *   The store addresses corners by GLOBAL col/row where col 0 is world
 *   `layer.origin.x` (which is -1600 in the shipped map), so
 *       gridSpace G = col * cellSize
 *       trueWorld  = layer.origin.x + G
 *   Every number in this file is in GRID SPACE G. The editor's own tool
 *   functions (scatterStroke, applyTerrainPaint) take TRUE world, so calls into
 *   them convert with `tx()` / `tz()`. Mixing these up silently writes the edit
 *   1600 units away.
 */

import { TERRAIN_MATERIALS, type TerrainMaterial } from '../src/terrain/index.js';
import type { MapChunkStore } from '../src/terrain/map-world.js';
import { resculptMaterial } from '../src/render/iso3d/editor/brush.js';
import { scatterStroke } from '../src/render/iso3d/editor/scatter.js';
import type { PropKind } from '../src/terrain/vegetation.js';
import { Rng } from '../src/shared/prng.js';

const MAT = (name: TerrainMaterial): number => TERRAIN_MATERIALS.indexOf(name);

/** A point in grid space. See the coordinate note above. */
type Pt = readonly [number, number];

/**
 * An index that cannot be missing, said out loud.
 *
 * `noUncheckedIndexedAccess` types every array read as possibly `undefined`, and
 * every one of these is inside a loop bounded by that same array's length. A
 * `?? 0` would paper over an impossible case by quietly writing a wrong height;
 * this throws instead, so the impossible case stays impossible rather than
 * becoming a hard-to-see edit to the terrain.
 */
function must<T>(value: T | undefined, what: string): T {
  if (value === undefined) throw new Error(`${what} is missing`);
  return value;
}

/* ------------------------------------------------------------------ noise */

function hash2(a: number, b: number): number {
  const n = Math.sin(a * 127.1 + b * 311.7) * 43758.5453;
  return n - Math.floor(n);
}
function vnoise(x: number, z: number, s: number): number {
  const X = x / s, Z = z / s;
  const x0 = Math.floor(X), z0 = Math.floor(Z);
  const fx = X - x0, fz = Z - z0;
  const sx = fx * fx * (3 - 2 * fx), sz = fz * fz * (3 - 2 * fz);
  const a = hash2(x0, z0), b = hash2(x0 + 1, z0), c = hash2(x0, z0 + 1), d = hash2(x0 + 1, z0 + 1);
  const top = a + (b - a) * sx, bot = c + (d - c) * sx;
  return top + (bot - top) * sz;
}

/* ------------------------------------------------------- geometry constants */

export const NODES = {
  hub:        [1950, 1900],
  pens:       [1950, 1620],
  raccoon:    [1050, 1180],
  warren:     [ 500,  800],
  ford:       [ 900, 2450],
  cross:      [2650, 1750],
  bone:       [3000, 2350],
  ridge:      [4950, 1650],
  palisade:   [5900, 2750],
  farwarren:  [5800,  700],
  stairfoot:  [4980,  120],
  summit:     [5600, -2150],
  beach:      [9550, 2550],
} as const satisfies Record<string, Pt>;

/** The node names, so an edge cannot name a place that is not on the map. */
export type NodeName = keyof typeof NODES;

/** Lowland roads. The mountain road is generated separately. */
export const EDGES: readonly (readonly [NodeName, NodeName])[] = [
  ['hub', 'pens'], ['hub', 'raccoon'], ['raccoon', 'warren'],
  ['hub', 'ford'], ['ford', 'bone'], ['hub', 'cross'], ['cross', 'bone'],
  ['cross', 'ridge'], ['ridge', 'palisade'], ['ridge', 'farwarren'],
  ['farwarren', 'stairfoot'], ['palisade', 'beach'],
];

const CIRQUE: Pt = [5600, -2150];
const HORN: Pt = [5230, -2690];

/* ----------------------------------------------------------------- helpers */

function makeAccess(store: MapChunkStore, layerId: string) {
  const cell = store.cellSize;
  const layer = store.layerInfo(layerId);
  // The one guard the untyped version left to a TypeError deeper in. Every
  // caller passes a layer that exists, so this never fires; it is here because
  // `layerInfo` is honest about answering `undefined` and `layer.origin` below
  // is not a place to find that out.
  if (!layer) throw new Error(`no such layer: ${layerId}`);
  const col = (x: number): number => Math.round(x / cell);
  const row = (z: number): number => Math.round(z / cell);
  return {
    cell, layer, col, row,
    tx: (x: number): number => layer.origin.x + x,
    tz: (z: number): number => layer.origin.z + z,
    cH: (c: number, r: number): number => store.cornerHeight(layerId, c, r),
    sH: (c: number, r: number, v: number): void => store.setCornerHeight(layerId, c, r, v),
    H: (x: number, z: number): number => store.cornerHeight(layerId, col(x), row(z)),
    cellIdx: (x: number): number => Math.floor(x / cell),
    setMat(x: number, z: number, m: number): boolean {
      const c = Math.floor(x / cell), r = Math.floor(z / cell);
      const at = store.cellAt(layerId, c, r);
      if (!at || at.materialIndex === m) return false;
      store.setCellMaterial(layerId, c, r, m);
      return true;
    },
    matAt(x: number, z: number): number | null {
      const at = store.cellAt(layerId, Math.floor(x / cell), Math.floor(z / cell));
      return at ? at.materialIndex : null;
    },
  };
}

/** What {@link makeAccess} hands back, so the passes below can be annotated. */
type Access = ReturnType<typeof makeAccess>;

/** Re-run the terrain brush's own material rule over a col/row rect. */
function resculpt(
  store: MapChunkStore,
  layerId: string,
  A: Access,
  c0: number,
  r0: number,
  c1: number,
  r1: number,
): number {
  const { cell, layer } = A;
  let n = 0;
  for (let row = r0; row <= r1; row++) {
    for (let col = c0; col <= c1; col++) {
      const stored = store.cellAt(layerId, col, row);
      if (!stored) continue;
      const h00 = A.cH(col, row), h10 = A.cH(col + 1, row);
      const h01 = A.cH(col, row + 1), h11 = A.cH(col + 1, row + 1);
      const dx = (h10 + h11 - h00 - h01) / (2 * cell);
      const dz = (h01 + h11 - h00 - h10) / (2 * cell);
      const next = resculptMaterial(
        stored.materialIndex, (h00 + h10 + h01 + h11) / 4, Math.hypot(dx, dz), layer.waterLevel,
      );
      if (next !== stored.materialIndex) { store.setCellMaterial(layerId, col, row, next); n++; }
    }
  }
  return n;
}

/* ------------------------------------------------------ 1. the mountain mass */

export function sculptFlank(store: MapChunkStore, layerId: string): { raised: number; maxH: number } {
  const A = makeAccess(store, layerId);
  const X0 = 4100, X1 = 7100, Z0 = -1780, Z1 = 260;
  let raised = 0, maxH = 0;
  for (let row = A.row(Z0); row <= A.row(Z1); row++) {
    for (let col = A.col(X0); col <= A.col(X1); col++) {
      const x = col * A.cell, z = row * A.cell;
      const t = Math.min(1, Math.max(0, (100 - z) / 1800));
      const hbase = 20 + 755 * Math.pow(t, 1.55);
      const xc = 5600 + 200 * Math.sin(t * 3.0);
      const w = 1500 - 380 * t;
      const u = Math.abs(x - xc) / w;
      const shape = u >= 1 ? 0 : Math.pow(Math.cos((u * Math.PI) / 2), 0.8);
      let h = -160 + (hbase + 160) * shape;
      if (shape > 0.02) {
        const n = (vnoise(x, z, 340) - 0.5) * 2;
        const gully = Math.pow(Math.abs(Math.sin((x - xc) / 210 + t * 1.4)), 1.6);
        h += n * 46 * t + (gully - 0.5) * 54 * t * shape;
      }
      const cur = A.cH(col, row);
      if (cur != null && h > cur) { A.sH(col, row, h); raised++; if (h > maxH) maxH = h; }
    }
  }
  return { raised, maxH: Math.round(maxH) };
}

/* ---------------------------------- 2. summit: cirque, headwall, horn, arete */

export function sculptSummit(store: MapChunkStore, layerId: string): { carved: number; lifted: number; peak: number } {
  const A = makeAccess(store, layerId);
  const cl = (v: number, a: number, b: number): number => Math.min(b, Math.max(a, v));
  let carved = 0, lifted = 0, peak = 0;
  for (let row = A.row(-3250); row <= A.row(-1500); row++) {
    for (let col = A.col(4300); col <= A.col(7100); col++) {
      const x = col * A.cell, z = row * A.cell, cur = A.cH(col, row);
      if (cur == null) continue;
      let t = cur;
      const d = Math.hypot(x - CIRQUE[0], z - CIRQUE[1]);
      if (d < 780) {
        const bt = cl((780 - d) / 340, 0, 1);
        const floor = 668 + 46 * Math.pow(1 - bt, 2) + 14 * vnoise(x, z, 190);
        const nt = t + (floor - t) * bt;
        if (nt < t) { t = nt; carved++; }
      }
      const southness = cl((z + 1930) / 260, 0, 1);
      const ring = Math.exp(-Math.pow((d - 830) / 240, 2));
      t = Math.max(t, t + (826 + 66 * vnoise(x, z, 240) - t) * ring * (1 - southness));
      const dh = Math.hypot(x - HORN[0], z - HORN[1]);
      if (dh < 540) {
        const ht = Math.pow(1 - dh / 540, 1.6);
        t = Math.max(t, t + (946 + 40 * vnoise(x, z, 150) - t) * ht);
      }
      const da = Math.abs(z + 2620);
      if (x >= 5230 && x <= 6200 && da < 160) {
        const at = Math.pow(1 - da / 160, 1.3);
        t = Math.max(t, t + (880 + 30 * vnoise(x, z, 120) - t) * at);
      }
      if (t !== cur) { A.sH(col, row, t); if (t > cur) lifted++; if (t > peak) peak = t; }
    }
  }
  return { carved, lifted, peak: Math.round(peak) };
}

/* ------------------------------------------------- 3. the serpentine road */

export function serpentine(store: MapChunkStore, layerId: string): Road {
  const A = makeAccess(store, layerId);
  const XA = 4980, XB = 6240, ZTOP = 100, DZ = 260, LEGS = 7;
  const pts: Pt[] = [];
  const push = (x: number, z: number): void => {
    const p = pts[pts.length - 1];
    if (!p || Math.hypot(x - p[0], z - p[1]) > 6) pts.push([x, z]);
  };
  for (let i = 0; i < LEGS; i++) {
    const z = ZTOP - i * DZ, l2r = i % 2 === 0;
    const from = l2r ? XA : XB, to = l2r ? XB : XA;
    const steps = Math.ceil(Math.abs(to - from) / 14);
    for (let s = 0; s <= steps; s++) push(from + ((to - from) * s) / steps, z);
    if (i < LEGS - 1) {
      const cz = z - DZ / 2, dir = l2r ? 1 : -1, r = DZ / 2;
      // +PI/2 -> -PI/2 so the arc leaves this leg and arrives at the next one.
      for (let a = 1; a < 28; a++) {
        const th = Math.PI / 2 - (a / 28) * Math.PI;
        push(to + dir * r * Math.cos(th) * 1.18, cz + r * Math.sin(th));
      }
    }
  }
  const last = must(pts[pts.length - 1], 'the road\'s last point'), target: Pt = [5600, -1790];
  const n = Math.ceil(Math.hypot(target[0] - last[0], target[1] - last[1]) / 14);
  for (let s = 1; s <= n; s++) {
    push(last[0] + ((target[0] - last[0]) * s) / n, last[1] + ((target[1] - last[1]) * s) / n);
  }
  let len = 0; const cum = [0];
  for (let i = 1; i < pts.length; i++) {
    const a = must(pts[i - 1], `road point ${i - 1}`), b = must(pts[i], `road point ${i}`);
    len += Math.hypot(b[0] - a[0], b[1] - a[1]);
    cum.push(len);
  }
  const H0 = 24, H1 = Math.round(A.H(5600, -1790));
  return { pts, heights: cum.map((c) => H0 + (H1 - H0) * (c / len)), len, H0, H1, hairpins: LEGS - 1 };
}

/** A hit from {@link spatial}: how far, which point, and at what bearing. */
type Near = readonly [number, number, number];
/** Every road point within `rad` of a place. */
type Gather = (x: number, z: number, rad: number) => Near[];

function spatial(pts: readonly Pt[], GRID = 140): Gather {
  const g = new Map<string, number[]>();
  pts.forEach((p, i) => {
    const k = `${Math.floor(p[0] / GRID)}_${Math.floor(p[1] / GRID)}`;
    const bucket = g.get(k);
    if (bucket) bucket.push(i);
    else g.set(k, [i]);
  });
  return (x, z, rad) => {
    const out: Near[] = [];
    const gx = Math.floor(x / GRID), gz = Math.floor(z / GRID), n = Math.ceil(rad / GRID);
    for (let a = -n; a <= n; a++) {
      for (let b = -n; b <= n; b++) {
        const arr = g.get(`${gx + a}_${gz + b}`);
        if (!arr) continue;
        for (const i of arr) {
          const p = must(pts[i], `road point ${i}`), d = Math.hypot(p[0] - x, p[1] - z);
          if (d <= rad) out.push([d, i, Math.atan2(p[1] - z, p[0] - x)]);
        }
      }
    }
    return out;
  };
}

/** What {@link serpentine} lays out, and what the two passes after it read. */
export interface Road {
  readonly pts: readonly Pt[];
  readonly heights: readonly number[];
  readonly len: number;
  readonly H0: number;
  readonly H1: number;
  readonly hairpins: number;
}

/** Cut the road bench, filling the hollow inside each hairpin. */
export function cutBench(
  store: MapChunkStore,
  layerId: string,
  road: Road,
): { filled: number; benched: number; gather: Gather } {
  const A = makeAccess(store, layerId);
  const { pts, heights } = road;
  const gather = spatial(pts);
  const RS = 430, BENCH = 44, BLEND = 150;
  let filled = 0, benched = 0;
  for (let row = A.row(-1980); row <= A.row(280); row++) {
    for (let col = A.col(4700); col <= A.col(6560); col++) {
      const x = col * A.cell, z = row * A.cell, cur = A.cH(col, row);
      if (cur == null) continue;
      const found = gather(x, z, RS);
      if (!found.length) continue;
      let bd = Infinity, bi = -1, sw = 0, sh = 0;
      for (const [d, i] of found) {
        if (d < bd) { bd = d; bi = i; }
        const w = 1 / (d * d + 900);
        sw += w; sh += w * must(heights[i], `road height ${i}`);
      }
      const angs = found.map((f) => f[2]).sort((a, b) => a - b);
      let maxGap = 0;
      for (let i = 0; i < angs.length; i++) {
        const a = must(angs[i], `bearing ${i}`);
        const b = i + 1 < angs.length
          ? must(angs[i + 1], `bearing ${i + 1}`)
          : must(angs[0], 'the first bearing') + 2 * Math.PI;
        maxGap = Math.max(maxGap, b - a);
      }
      let h = cur;
      if (maxGap < 2.5) { h = sh / sw; filled++; }
      if (bd <= BENCH) { h = must(heights[bi], `road height ${bi}`); benched++; }
      else if (bd <= BLEND) {
        const w = 1 - (bd - BENCH) / (BLEND - BENCH);
        h += (must(heights[bi], `road height ${bi}`) - h) * (w * w * (3 - 2 * w));
      }
      if (h !== cur) A.sH(col, row, h);
    }
  }
  return { filled, benched, gather };
}

/** Surface the road, dithered at the edge the way the paint tool does. */
export function surfaceRoad(
  store: MapChunkStore,
  layerId: string,
  gather: Gather,
  box: readonly [number, number, number, number],
): number {
  const A = makeAccess(store, layerId);
  const DIRT = MAT('dirt');
  let n = 0;
  for (let row = A.row(box[2]); row <= A.row(box[3]); row++) {
    for (let col = A.col(box[0]); col <= A.col(box[1]); col++) {
      const x = col * A.cell + A.cell / 2, z = row * A.cell + A.cell / 2;
      const f = gather(x, z, 70);
      if (!f.length) continue;
      let bd = Infinity;
      for (const [d] of f) if (d < bd) bd = d;
      const edge = 46 + 8 * (hash2(col, row) - 0.5) * 2;
      if (bd <= edge && A.setMat(x, z, DIRT)) n++;
    }
  }
  return n;
}

/* ---------------------------------------------------------- 4. talus fans */

export function screeFans(store: MapChunkStore, layerId: string): { fans: number; lifted: number; painted: number } {
  const A = makeAccess(store, layerId);
  const ROCK = MAT('rock');
  const down = (x: number, z: number): Pt => {
    const e = 44;
    const gx = A.H(x + e, z) - A.H(x - e, z), gz = A.H(x, z + e) - A.H(x, z - e);
    const m = Math.hypot(gx, gz) || 1;
    return [-gx / m, -gz / m];
  };
  // A fan is where it starts, how far it runs and how high it heaps.
  const fans: (readonly [number, number, number, number])[] = [];
  for (let a = 0; a < 10; a++) {
    const th = Math.PI * 0.15 + a * ((Math.PI * 1.7) / 9);
    fans.push([CIRQUE[0] + 660 * Math.cos(th), CIRQUE[1] + 660 * Math.sin(th), 300, 62]);
  }
  for (let a = 0; a < 4; a++) {
    const th = (a * Math.PI) / 2 + 0.6;
    fans.push([HORN[0] + 430 * Math.cos(th), HORN[1] + 430 * Math.sin(th), 280, 58]);
  }
  const feet: readonly Pt[] = [
    [4780, -900], [6420, -760], [4760, -260], [6440, -1500], [5050, -1650], [6180, -160],
  ];
  for (const p of feet) {
    fans.push([p[0], p[1], 260, 48]);
  }
  let lifted = 0, painted = 0;
  for (const [fx, fz, LEN, AMP] of fans) {
    const [dx, dz] = down(fx, fz);
    if (!Number.isFinite(dx)) continue;
    const px = -dz, pz = dx;
    for (let s = 0; s <= LEN; s += A.cell / 2) {
      const t = s / LEN, halfW = 26 + LEN * 0.44 * t;
      for (let o = -halfW; o <= halfW; o += A.cell / 2) {
        const x = fx + dx * s + px * o, z = fz + dz * s + pz * o;
        const col = A.col(x), row = A.row(z), cur = A.cH(col, row);
        if (cur == null || cur <= -40) continue;
        const lat = 1 - Math.min(1, Math.abs(o) / halfW);
        const prof = Math.pow(1 - t, 1.9) * Math.pow(lat, 1.3);
        const add = AMP * prof * (0.75 + 0.5 * vnoise(x, z, 60));
        if (add > 0.6) { A.sH(col, row, cur + add); lifted++; }
        if (prof > 0.1 && A.setMat(x, z, ROCK)) painted++;
      }
    }
  }
  return { fans: fans.length, lifted, painted };
}

/* --------------------------------------------------------- 5. the treeline */

export function vegetate(
  store: MapChunkStore,
  layerId: string,
  gather: Gather,
  seed = 20260907,
): { strokes: number; added: number } {
  const A = makeAccess(store, layerId);
  let rng = Rng.fromSeed(seed);
  let added = 0, strokes = 0;
  for (let x = 4180; x <= 7020; x += 75) {
    for (let z = 240; z >= -1980; z -= 75) {
      const h = A.H(x, z);
      if (h == null || h <= 12 || h >= 520) continue;
      if (gather(x, z, 62).length > 0) continue;
      let species: PropKind, density: number;
      if (h < 150) { species = (x * 3 + z) % 200 < 130 ? 'tree' : 'bush'; density = 5; }
      else if (h < 300) { species = (x + z * 2) % 240 < 110 ? 'tree' : 'bush'; density = 4; }
      else if (h < 430) { species = 'bush'; density = 3; }
      else { species = 'bush'; density = 1; }
      const res = scatterStroke(store, layerId, {
        species, density,
        maxSlope: species === 'tree' ? 0.6 : 0.85,
        scaleMin: h > 300 ? 0.45 : 0.8,
        scaleMax: h > 300 ? 0.85 : 1.5,
        spacing: species === 'tree' ? 30 : 20,
        alignToNormal: false,
      }, { x: A.tx(x), z: A.tz(z), radius: 60, dtSeconds: 1, carry: 0, onTouchChunk: () => undefined }, rng);
      if (res.rng) rng = res.rng;
      added += res.added ? res.added.length : 0;
      strokes++;
    }
  }
  return { strokes, added };
}

/* ------------------------------------------- 6. the Warden's beach arena */

export function beachArena(store: MapChunkStore, layerId: string): { shaped: number; mats: number } {
  const A = makeAccess(store, layerId);
  const [BX, BZ] = NODES.beach;
  const ROCK = MAT('rock'), SAND = MAT('sand');
  let shaped = 0;
  for (let row = A.row(BZ - 760); row <= A.row(BZ + 760); row++) {
    for (let col = A.col(BX - 760); col <= A.col(BX + 760); col++) {
      const x = col * A.cell, z = row * A.cell, cur = A.cH(col, row);
      if (cur == null) continue;
      const d = Math.hypot(x - BX, z - BZ);
      const ang = Math.atan2(z - BZ, x - BX);
      let t = cur;
      // shallow arena floor
      if (d < 430) t = Math.min(t, 14 + 5 * vnoise(x, z, 90));
      // broken rim, with gaps where the causeway and the sea come in
      const gap = Math.min(
        Math.abs(((ang + Math.PI * 2.35) % (Math.PI * 2)) - Math.PI),
        Math.abs(((ang + Math.PI * 0.9) % (Math.PI * 2)) - Math.PI),
      );
      const gate = Math.min(1, gap / 0.42);
      const ring = Math.exp(-Math.pow((d - 470) / 105, 2));
      const rim = 96 + 44 * vnoise(x, z, 70);
      t = Math.max(t, t + (rim - t) * ring * gate);
      // central dais the Warden stands on
      if (d < 120) t = Math.max(t, 30 + 8 * Math.pow(1 - d / 120, 2));
      if (t !== cur) { A.sH(col, row, t); shaped++; }
    }
  }
  // rim reads as rock, floor as sand
  let mats = 0;
  for (let row = A.row(BZ - 700); row <= A.row(BZ + 700); row++) {
    for (let col = A.col(BX - 700); col <= A.col(BX + 700); col++) {
      const x = col * A.cell, z = row * A.cell;
      const d = Math.hypot(x - BX, z - BZ);
      if (d > 560) continue;
      const want = d > 400 ? ROCK : SAND;
      if (A.setMat(x, z, want)) mats++;
    }
  }
  return { shaped, mats };
}

/* --------------------------------------------------- 7. lowland dirt roads */

export function lowlandRoads(
  store: MapChunkStore,
  layerId: string,
): { painted: number; per: Record<string, number> } {
  const A = makeAccess(store, layerId);
  const DIRT = MAT('dirt'), GRASS = MAT('grass'), SAND = MAT('sand');
  let painted = 0;
  const per: Record<string, number> = {};
  for (const [a, b] of EDGES) {
    const P = NODES[a], Q = NODES[b];
    const dx = Q[0] - P[0], dz = Q[1] - P[1];
    const len = Math.hypot(dx, dz), steps = Math.ceil(len / 8);
    let n = 0;
    for (let s = 0; s <= steps; s++) {
      const t = s / steps, x = P[0] + dx * t, z = P[1] + dz * t;
      for (let ox = -34; ox <= 34; ox += A.cell / 2) {
        for (let oz = -34; oz <= 34; oz += A.cell / 2) {
          if (Math.hypot(ox, oz) > 34) continue;
          const m = A.matAt(x + ox, z + oz);
          if (m !== GRASS && m !== SAND) continue;
          if (A.setMat(x + ox, z + oz, DIRT)) n++;
        }
      }
    }
    per[`${a}->${b}`] = n;
    painted += n;
  }
  return { painted, per };
}

/* ------------------------------------------------------------- entry point */

export function authorTerrain(store: MapChunkStore, layerId: string) {
  const A = makeAccess(store, layerId);
  const flank = sculptFlank(store, layerId);
  const summit = sculptSummit(store, layerId);
  const road = serpentine(store, layerId);
  const bench = cutBench(store, layerId, road);
  // Built as one object rather than assigned field by field, which is the only
  // thing in this file the annotations changed the shape of: an empty `{}` has
  // no such properties to write, and inventing an interface for a report nobody
  // reads twice would be more ceremony than the report is worth.
  const report = {
    flank,
    summit,
    road: {
      points: road.pts.length,
      length: Math.round(road.len),
      climb: road.H1 - road.H0,
      gradePct: +(((road.H1 - road.H0) / road.len) * 100).toFixed(2),
      hairpins: road.hairpins,
    },
    bench: { filled: bench.filled, benched: bench.benched },
    scree: screeFans(store, layerId),
    beach: beachArena(store, layerId),
    resculpt:
      resculpt(store, layerId, A, A.col(4100), A.row(-3250), A.col(7100), A.row(320)) +
      resculpt(store, layerId, A, A.col(8800), A.row(1800), A.col(10300), A.row(3300)),
    roadSurface: surfaceRoad(store, layerId, bench.gather, [4700, 6560, -1980, 300]),
    veg: vegetate(store, layerId, bench.gather),
    lowlandRoads: lowlandRoads(store, layerId),
  };
  return { report, road };
}
