/**
 * Build step: decode the vendored pixeldudesmaker atlases into a pure-data TS
 * module (`src/render/dude-atlas.ts`) the runtime baker can consume with no PNG
 * decoder and no colour matching. Run via `npm run bake:sprites`.
 *
 * Every distinct source colour is classified once here (into a recolour channel
 * or kept literal), so at runtime a dude is just: composite indices, then map
 * each index to an RGBA through the seed-chosen palette. See specs/011.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PNG } from 'pngjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA = join(HERE, '..', 'tools', 'pixeldudesmaker', 'data');
const OUT = join(HERE, '..', 'src', 'render', 'dude-atlas.ts');

interface Conf {
  w: number;
  h: number;
  outlineColor: string | [number, number, number];
  fromColors: Record<string, [number, number, number]>;
  pals: Record<string, string[]>;
  parts: Record<string, Record<string, number[]>>;
  bodyShadowMod?: number;
  hairShadowMod?: number;
  itemShadowMod?: number;
  suitShadowMod?: number;
}

const conf = JSON.parse(readFileSync(join(DATA, 'conf.json'), 'utf8')) as Conf;
const W = conf.w;
const H = conf.h;

// Recolour channels, in the order app.js tests them. Index here == channel id.
const CHANNELS = ['outline', 'eyes', 'skin', 'skin2', 'hair', 'hair2', 'item', 'item2', 'suit', 'suit2'] as const;
const LITERAL = -1;

// app.js matches source colours with a ±1 tolerance per component.
const near = (a: number, b: number): boolean => a === b || a === b - 1 || a === b + 1;
function classify(r: number, g: number, b: number): number {
  for (let c = 0; c < CHANNELS.length; c++) {
    const k = conf.fromColors[CHANNELS[c] as string] as [number, number, number];
    if (near(k[0], r) && near(k[1], g) && near(k[2], b)) return c;
  }
  return LITERAL;
}

const load = (name: string): PNG => PNG.sync.read(readFileSync(join(DATA, name)));
const base = load('base.png');
const heads = load('heads.png');
const faces = load('faces.png');

// Global source-colour table. Index 0 is reserved for transparent.
const srcTable: [number, number, number, number][] = [[-2, 0, 0, 0]];
const srcIndex = new Map<string, number>();
function indexOf(r: number, g: number, b: number, a: number): number {
  if (a === 0) return 0;
  const key = `${r},${g},${b}`;
  let idx = srcIndex.get(key);
  if (idx === undefined) {
    idx = srcTable.length;
    srcTable.push([classify(r, g, b), r, g, b]);
    srcIndex.set(key, idx);
  }
  return idx;
}

function pack(png: PNG): Uint8Array {
  const out = new Uint8Array(png.width * png.height);
  for (let p = 0; p < out.length; p++) {
    const i = p * 4;
    out[p] = indexOf(
      png.data[i] as number,
      png.data[i + 1] as number,
      png.data[i + 2] as number,
      png.data[i + 3] as number,
    );
  }
  return out;
}

const basePx = pack(base);
const headsPx = pack(heads);
const facesPx = pack(faces);
if (srcTable.length > 256) throw new Error(`source colours ${srcTable.length} exceed one byte`);

const b64 = (bytes: Uint8Array): string => Buffer.from(bytes).toString('base64');
const outlineHex = typeof conf.outlineColor === 'string' ? conf.outlineColor : null;
const outline = outlineHex
  ? [parseInt(outlineHex.slice(1, 3), 16), parseInt(outlineHex.slice(3, 5), 16), parseInt(outlineHex.slice(5, 7), 16)]
  : (conf.outlineColor as number[]);
const palette = (conf.pals.body ?? []).map((hex) => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
]);

const tuple = (a: number[]): string => `[${a.join(', ')}]`;
const src = srcTable.map(tuple).join(', ');
const pal = palette.map(tuple).join(', ');

const ts = `// GENERATED by scripts/bake-dude-atlas.ts — do not edit by hand.
// Source atlases: tools/pixeldudesmaker (generator by 0x72, used with permission).
//
// Channel ids in SRC: 0 outline, 1 eyes, 2 skin, 3 skin2, 4 hair, 5 hair2,
// 6 item, 7 item2, 8 suit, 9 suit2; -1 literal (kept as-is); -2 transparent.
// SRC[0] is the reserved transparent entry; atlas pixels are indices into SRC.

export const SPRITE_W = ${W};
export const SPRITE_H = ${H};

export const N_BASE = ${base.height / H};
export const N_HEAD = ${heads.width / W};
export const N_FACE = ${faces.width / W};

// base.png: columns are animation frames, rows are body variants.
export const IDLE_COLS: readonly number[] = [2, 3, 4, 5];
export const RUN_COLS: readonly number[] = [7, 8, 9, 10];

// Per-part vertical bob offset, indexed [anim][frame].
export const PART_OY = ${JSON.stringify(conf.parts)} as const;

export const OUTLINE: readonly [number, number, number] = ${tuple(outline)};
export const PALETTE: readonly (readonly [number, number, number])[] = [${pal}];
export const SHADOW = {
  body: ${conf.bodyShadowMod ?? 0.5}, hair: ${conf.hairShadowMod ?? 0.5},
  item: ${conf.itemShadowMod ?? 0.5}, suit: ${conf.suitShadowMod ?? 0.5},
} as const;

// [channel, r, g, b] per source colour; r,g,b only meaningful for literal (-1).
export const SRC: readonly (readonly [number, number, number, number])[] = [${src}];

export const BASE_W = ${base.width};
export const BASE_H = ${base.height};
export const HEADS_W = ${heads.width};
export const HEADS_H = ${heads.height};
export const FACES_W = ${faces.width};
export const FACES_H = ${faces.height};

// Row-major per-pixel indices into SRC, base64-packed (one byte per pixel).
export const BASE_PX = '${b64(basePx)}';
export const HEADS_PX = '${b64(headsPx)}';
export const FACES_PX = '${b64(facesPx)}';
`;

writeFileSync(OUT, ts);
console.log(
  `wrote ${OUT}\n  bases=${base.height / H} heads=${heads.width / W} faces=${faces.width / W} ` +
    `srcColours=${srcTable.length} (literal=${srcTable.filter((s) => s[0] === -1).length})`,
);
