/**
 * Writes the reference unit into `assets/units/dev/` (spec 110).
 *
 *   npx tsx scripts/make-reference-unit.ts
 *
 * Everything it writes is committed, which is the point: a fresh clone can open
 * the Studio tab and see a real skinned biped move, and the deformation and
 * screenshot checks have a subject before a single credit has been spent.
 *
 * The shape of the work is `src/units/reference-unit.ts`, which is pure and
 * tested. This file is only the part that cannot be: turning it into bytes and
 * putting them on disk, then validating the result the same way CI will.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeGlb } from '../src/units/glb.js';
import { buildReferenceUnit } from '../src/units/reference-unit.js';
import { formatIssue } from '../src/units/issues.js';
import { validateClipLib, validateSkeleton, validateUnitBundle, validateUnitDef } from '../src/units/validate.js';
import type { ClipLib, UnitDef } from '../src/units/types.js';
// The constant rather than `biped.skeleton.json`, which is the *canonical
// family's* document and is now rewritten by the Studio export the first time a
// real rig is measured (spec 115). The reference unit must not depend on a file
// somebody else's generation can change.
import { DEFAULT_CANONICAL_HEIGHT } from '../src/units/canonical-height.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'assets', 'units', 'dev');
const clipDir = join(outDir, 'clips');

/**
 * A fixed stamp rather than the clock.
 *
 * The generated documents are committed, so a regeneration that changed nothing
 * has to produce no diff. A real timestamp would make every run a change, and a
 * provenance date on a unit nobody paid for would be pretending anyway.
 */
const GENERATED_AT = '2026-01-01T00:00:00Z';

function write(path: string, bytes: Uint8Array | string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, bytes);
  console.log(`  wrote ${path.slice(root.length + 1)}`);
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function main(): void {
  mkdirSync(clipDir, { recursive: true });
  const unit = buildReferenceUnit(DEFAULT_CANONICAL_HEIGHT);

  write(join(outDir, 'mannequin.glb'), writeGlb(unit.meshGlb));
  for (const clip of unit.clipGlbs) write(join(clipDir, `${clip.id}.glb`), writeGlb(clip.document));
  write(join(outDir, 'mannequin-dev.skeleton.json'), json(unit.skeleton));

  const clipLib: ClipLib = {
    $comment: 'Generated by scripts/make-reference-unit.ts (spec 110). Durations are what the clips were authored at.',
    formatVersion: 1,
    id: 'mannequin-dev.core',
    skeletonRef: 'mannequin-dev.skeleton.json',
    clips: unit.clips,
  };
  write(join(outDir, 'mannequin-dev.core.cliplib.json'), json(clipLib));

  /**
   * The import scale is **measured**, not chosen: the canonical height divided
   * by what the model was actually authored at. That is the number the first
   * real unit will need too, and it is around thirty -- which is why a hardcoded
   * 1 somewhere would put a body in this world the size of a coin.
   */
  const scale = DEFAULT_CANONICAL_HEIGHT / unit.authoredHeight;
  /** Counted off the mesh just written, so the document cannot claim otherwise. */
  const meshData = unit.meshGlb.mesh;
  if (!meshData) throw new Error('the reference unit built no mesh to count');
  const triangles = Math.round(meshData.indices.length / 3);

  const unitDef: UnitDef = {
    $comment:
      'The development reference unit (spec 110). Not generated by Tripo -- the provenance below is deliberately zeroed rather than faked, because a plausible task id in a committed file is worse than an obvious placeholder.',
    formatVersion: 1,
    id: 'mannequin',
    meshRef: 'mannequin.glb',
    skeletonRef: 'mannequin-dev.skeleton.json',
    clipLibRef: 'mannequin-dev.core.cliplib.json',
    provenance: {
      tripoTaskIds: { imageToModel: 'local-reference', rigCheck: 'local-reference', rig: null, retarget: [] },
      modelVersion: 'local-reference',
      faceLimit: 2000,
      // The sha256 of the empty string: a real hash of nothing, which is what
      // this was generated from. It can never collide with a real image's.
      referenceImageSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      creditsSpent: 0,
      generatedAt: GENERATED_AT,
    },
    // Counted off the mesh this script just built, never declared.
    // `provenance.faceLimit` above is what a generation would have been *asked*
    // for; `targetTris` is what the asset actually is, and the bake gates on the
    // difference. They were both 2000 here, and the mannequin has 156 -- the
    // first thing `npm run bake:units` ever did was refuse it.
    import: { normals: 'flat', targetTris: triangles, scale, upAxis: '+Y' },
    maxTimeScale: 2,
    stateMachine: {
      parameters: [
        { name: 'speed', type: 'float' },
        { name: 'attack', type: 'trigger' },
        { name: 'dead', type: 'bool' },
      ],
      states: [
        { id: 'idle', clipRef: 'idle', loop: true, timeScale: 1, blendInMs: 150, category: 'loop' },
        { id: 'locomotion', clipRef: 'move', loop: true, timeScale: 1, blendInMs: 150, category: 'loop' },
        // Locking: committing to a blow means being committed to it, which is
        // the decision this whole game is built on.
        { id: 'swing', clipRef: 'slash', loop: false, timeScale: 1, blendInMs: 60, category: 'locking' },
        { id: 'down', clipRef: 'slash', loop: false, timeScale: 0.6, blendInMs: 200, category: 'terminal' },
      ],
      blendTrees: [
        {
          id: 'move',
          parameter: 'speed',
          // The thresholds the humanoid rig already walks and runs at, so the
          // blend agrees with the gait the rest of the renderer uses.
          thresholds: [
            { value: 0, clipRef: 'idle' },
            { value: 34, clipRef: 'walk' },
            { value: 150, clipRef: 'run' },
          ],
        },
      ],
      transitions: [
        { from: 'idle', to: 'locomotion', condition: 'speed > 5', durationMs: 150, interruptible: true },
        { from: 'locomotion', to: 'idle', condition: 'speed < 5', durationMs: 150, interruptible: true },
        { from: '*', to: 'swing', condition: 'attack', durationMs: 60, interruptible: false },
        { from: 'swing', to: 'idle', condition: 'exit', durationMs: 120, interruptible: false },
        { from: '*', to: 'down', condition: 'dead', durationMs: 200, interruptible: true },
      ],
      actionTimings: [
        {
          actionId: 'basic.attack',
          // 900ms of clip over a 780ms action: a 1.15x rate, comfortably inside
          // the 2x limit, so this ships as a worked example rather than as an
          // edge case somebody has to fix before they can use it.
          windupMs: 380,
          activeMs: 120,
          recoveryMs: 280,
          // `slash` the clip, driven by the `attack` trigger above. The two names
          // are different on purpose: the trigger is what the game asks for, the
          // clip is what the API retargeted, and conflating them is how a unit
          // ends up needing a clip nobody can order.
          clipRef: 'slash',
          eventMap: { windup: 'swing.start', active: 'swing.impact' },
        },
      ],
    },
  };
  write(join(outDir, 'mannequin.unitdef.json'), json(unitDef));

  // --- validate exactly the way CI will -------------------------------------
  const issues = [
    ...validateSkeleton(unit.skeleton).issues,
    ...validateClipLib(clipLib).issues,
    ...validateUnitDef(unitDef).issues,
  ];
  const skeleton = validateSkeleton(unit.skeleton).value;
  const lib = validateClipLib(clipLib).value;
  const def = validateUnitDef(unitDef).value;
  if (skeleton && lib && def) issues.push(...validateUnitBundle({ unit: def, skeleton, clipLib: lib }));

  for (const issue of issues) console.log(`  ${formatIssue(issue)}`);
  const errors = issues.filter((issue) => issue.severity === 'error');
  console.log(
    `\n  authored ${unit.authoredHeight.toFixed(3)} units tall, import scale ${scale.toFixed(2)}x ` +
      `-> ${DEFAULT_CANONICAL_HEIGHT} world units`,
  );
  if (errors.length > 0) {
    console.error(`\n${errors.length} error(s); the reference unit is not valid`);
    process.exitCode = 1;
    return;
  }
  console.log('  the reference unit validates');
}

main();
