import type { RobeTuning } from '../cloth/params.js';
import type { TuningGroup } from './tuning-panel.js';

/**
 * The robe's tuning rows for the sandbox panel (spec 037).
 *
 * The *documentation* of what each knob means lives on the fields in
 * `cloth/params.ts`; this file is the UI surface for them -- practical slider
 * ranges (deliberately narrower than the safety bounds in `ROBE_BOUNDS`, which
 * exist only to catch garbage) and the hover text that makes the panel usable
 * without reading the source.
 *
 * Kept apart from `movement.ts` so the sandbox view stays a view: adding a
 * tunable is a row here and a field there, and nothing about mounting or
 * layout changes.
 */
export const ROBE_TUNING_GROUPS: readonly TuningGroup<RobeTuning>[] = [
  {
    title: 'Figure',
    rows: [
      {
        label: 'Size',
        key: 'bodyScale',
        min: 0.4,
        max: 2.5,
        step: 0.05,
        digits: 2,
        tip: 'Overall figure size. Scales the skeleton, the garments and every distance in the simulation together, so the fabric behaves the same at any size.',
      },
      {
        label: 'Stride length',
        key: 'strideScale',
        min: 0.4,
        max: 2,
        step: 0.05,
        digits: 2,
        tip: 'How far the figure travels per step. Lower means quicker, shorter steps at the same speed — which makes the lower robe swish faster.',
      },
      {
        label: 'Arm swing',
        key: 'armSwing',
        min: 0,
        max: 1.4,
        step: 0.05,
        digits: 2,
        tip: 'Arm-swing amplitude in radians at a full run. This is what drives the sleeves: the sleeves are pinned to the arms, so their motion is this swing plus the cloth solve.',
      },
      {
        label: 'Jump height',
        key: 'jumpHeight',
        min: 0,
        max: 180,
        step: 2,
        tip: 'How high the Jump button hops, in world units (the figure is ~84 tall). Higher jumps land harder, which drives a bigger landing flare.',
      },
    ],
  },
  {
    title: 'Fabric',
    rows: [
      {
        label: 'Fabric weight',
        key: 'fabricWeight',
        min: 0.15,
        max: 5,
        step: 0.05,
        digits: 2,
        tip: 'Mass of the cloth. Gravity is mass-independent, so this does not change how fast it falls — it changes how much the air can move it. Heavy fabric hangs close and swings slowly; light fabric flutters.',
      },
      {
        label: 'Stiffness',
        key: 'stiffness',
        min: 0,
        max: 1,
        step: 0.01,
        digits: 2,
        tip: 'How hard the weave resists being stretched. 1 is inextensible canvas; lower lets panels sag and give like knitwear.',
      },
      {
        label: 'Bend stiffness',
        key: 'bendStiffness',
        min: 0,
        max: 1,
        step: 0.01,
        digits: 2,
        tip: 'How hard the fabric resists folding, independently of stretching. Near 0 gives limp silk with many small folds; high gives stiff felt with a few broad ones. Keep it well below Stiffness — real cloth bends far more easily than it stretches.',
      },
      {
        label: 'Damping',
        key: 'damping',
        min: 0,
        max: 12,
        step: 0.05,
        digits: 2,
        tip: 'Internal friction in the weave. This is what makes a swing oscillate a few times and die out rather than ringing forever. Too low reads as rubbery, too high as underwater.',
      },
      {
        label: 'Max stretch',
        key: 'maxStretch',
        min: 1,
        max: 2,
        step: 0.01,
        digits: 2,
        tip: 'Hard cap on how far a particle may get from its attachment ring, as a multiple of its rest distance. Enforced after the solve, so no wind, speed or teleport can balloon the robe. 1 pins it flat to the body.',
      },
      {
        label: 'Spring strength',
        key: 'springStrength',
        min: 0,
        max: 20,
        step: 0.1,
        digits: 1,
        tip: 'Always-on pull toward the pose the garment would hang in if it were rigidly attached. This is the tailoring, not physics: it keeps the silhouette readable while moving. Strong at the seams, near zero at the hems.',
      },
      {
        label: 'Recovery speed',
        key: 'recoverySpeed',
        min: 0,
        max: 20,
        step: 0.1,
        digits: 1,
        tip: 'Extra settle toward the rest pose, faded in only while the figure is standing still. Raise it to have the robe come to rest promptly after moving; lower it to let it keep swinging.',
      },
    ],
  },
  {
    title: 'Forces',
    rows: [
      {
        label: 'Gravity ×',
        key: 'gravityMultiplier',
        min: 0,
        max: 3,
        step: 0.05,
        digits: 2,
        tip: 'Multiplier on real gravity (9.81 m/s², ~422 world units/s²). Below 1 reads as floaty, weightless fabric. Also scales the jump, so the hop keeps its height.',
      },
      {
        label: 'Air resistance',
        key: 'airResistance',
        min: 0,
        max: 8,
        step: 0.05,
        digits: 2,
        tip: 'Drag against the relative air velocity, in every direction. The main source of the trailing lag when the figure accelerates.',
      },
      {
        label: 'Wind influence',
        key: 'windInfluence',
        min: 0,
        max: 12,
        step: 0.1,
        digits: 1,
        tip: 'Wind pressure on the surface, projected onto each particle normal — so a panel broadside to the wind billows and an edge-on one slices through. This is what makes it read as fabric rather than a pushed rag.',
      },
      {
        label: 'Inertia ×',
        key: 'inertiaMultiplier',
        min: 0,
        max: 4,
        step: 0.05,
        digits: 2,
        tip: 'How strongly the loose fabric feels the figure accelerating underneath it. This is the whip on a hard direction change and the robe getting left behind on a sprint start. 1 is physically neutral; higher exaggerates.',
      },
      {
        label: 'Movement influence',
        key: 'movementInfluence',
        min: 0,
        max: 2,
        step: 0.05,
        digits: 2,
        tip: 'Extra headwind generated by the figure’s own travel. 0 is physically honest (the cloth’s own drag already streams it); above 0 exaggerates how much a run pins the robe backward.',
      },
      {
        label: 'Jump impulse',
        key: 'jumpImpulse',
        min: 0,
        max: 250,
        step: 5,
        tip: 'Downward kick given to the loose fabric at the moment of push-off, exaggerating how far the robe trails as the figure rises.',
      },
      {
        label: 'Landing impulse',
        key: 'landImpulse',
        min: 0,
        max: 250,
        step: 5,
        tip: 'Upward kick on touchdown, scaled by how hard the landing was — the outward flare as the body stops and the fabric keeps going.',
      },
      {
        label: 'Idle sway',
        key: 'idleSway',
        min: 0,
        max: 120,
        step: 1,
        tip: 'A slow per-particle noise force applied only while the figure is standing still, so the robe is never perfectly static. Pairs with the figure’s breathing.',
      },
    ],
  },
  {
    title: 'Wind',
    rows: [
      {
        label: 'Wind enabled',
        key: 'windEnabled',
        min: 0,
        max: 1,
        step: 1,
        toggle: true,
        tip: 'Turn the wind field on or off. Switching it off ramps the wind down smoothly rather than cutting it, so the robe settles instead of snapping.',
      },
      {
        label: 'Direction (°)',
        key: 'windDirection',
        min: -180,
        max: 180,
        step: 5,
        tip: 'Compass heading the wind blows toward: 0 is world +X, 90 is world +Z. Changes are eased in, and take the short way round.',
      },
      {
        label: 'Strength',
        key: 'windStrength',
        min: 0,
        max: 400,
        step: 5,
        tip: 'Sustained wind speed in world units/s. About 43 units/s is 1 m/s, so 130 is a brisk breeze and 400 is a gale.',
      },
      {
        label: 'Gust strength',
        key: 'gustStrength',
        min: 0,
        max: 400,
        step: 5,
        tip: 'Peak extra speed the gusts add on top of the sustained wind.',
      },
      {
        label: 'Gust rate (Hz)',
        key: 'gustFrequency',
        min: 0,
        max: 3,
        step: 0.05,
        digits: 2,
        tip: 'How often the gust envelope swells and drops. Low is long rolling gusts; high is choppy.',
      },
      {
        label: 'Turbulence',
        key: 'windTurbulence',
        min: 0,
        max: 1,
        step: 0.02,
        digits: 2,
        tip: 'How much the wind wanders in direction, and how much it varies across a single panel. 0 is a wind tunnel; 1 is messy and gusty.',
      },
      {
        label: 'Transition rate',
        key: 'windTransition',
        min: 0.05,
        max: 8,
        step: 0.05,
        digits: 2,
        tip: 'How fast direction and strength changes take effect (per second). Low makes the wind rise and die slowly — and is what stops a slider drag yanking the whole robe sideways.',
      },
    ],
  },
  {
    title: 'Collision & solver',
    collapsed: true,
    rows: [
      {
        label: 'Collision radius',
        key: 'collisionRadius',
        min: 0,
        max: 8,
        step: 0.1,
        digits: 1,
        tip: 'Extra clearance added to every body capsule when pushing cloth out of it. A small margin keeps the fabric visibly off the body and hides facets poking through.',
      },
      {
        label: 'Iterations',
        key: 'iterations',
        min: 1,
        max: 12,
        step: 1,
        tip: 'Constraint iterations per substep. The apparent stiffness is held constant as you change this, so it trades cost against how truly inextensible the weave is rather than changing the feel.',
      },
      {
        label: 'Substeps',
        key: 'substeps',
        min: 1,
        max: 6,
        step: 1,
        tip: 'Physics substeps per rendered frame. Mostly buys accuracy under fast motion; 2 is plenty for gameplay.',
      },
    ],
  },
];
